### PR TITLE
spelling mistake in Readme.md

### PR DESCRIPTION
**Pull request by RitikaSinghal18**
anayzle-->analyze

### CODE REVIEW

**Comment by darpa-muse** [comment]
thanks wont count towards hacktoberfest.

**Comment by RitikaSinghal18** [comment]
But why?

**Comment by darpa-muse** [comment]
Not a significant contribution, read more here
https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by RitikaSinghal18** [comment]
Hey, can you tell me if I made 5 pull requests but only 4 pr are in review
period and one of them is invalid , will hacktoberfest count the 5th pr in
review period automatically or not?

**Pull request closed without merging**
